/*  Copyright (c) 2016 SIGMusic @ UIUC
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef NOTE_HPP
#define NOTE_HPP

namespace GrandPiano
{

// MIDI note IDs
#define MIDI_C4 48
#define MIDI_D4 50
#define MIDI_E4 52
#define MIDI_F4 53
#define MIDI_G4 55
#define MIDI_A4 57
#define MIDI_B4 59
#define MIDI_C5 60
#define MIDI_CSHARP4 49
#define MIDI_DSHARP4 51
#define MIDI_FSHARP4 54
#define MIDI_GSHARP4 56
#define MIDI_ASHARP4 58

}

#endif /* NOTE_HPP */
